name: PREVIEW

on:
  issue_comment:
    types: [created]

jobs:
  request-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '预览'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.6.0'
      - run: cd miniprogram && npm install
        shell: bash
      - name: get preview qrcode
        id: preview
        uses: LeeJim/setup-miniprogram@main
        with:
          project_type: miniProgram
          action_type: preview
          need-pack-npm: true
          project_path: ./miniprogram
          version: ${{ github.ref_name }}
          es6: true
          es7: true
          minify: true
        env: 
          MINI_APP_ID: ${{ secrets.APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            <img alt="qrcode" src="${{ steps.preview.outputs.preview-qrcode }}" />
