name: PREVIEW

on:
  issue_comment:
    types: [created]

jobs:
  request-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '预览'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.6.0'
      - run: npm install & npm run build
        shell: bash
      - name: get preview qrcode
        id: preview
        uses: LeeJim/setup-miniprogram@main
        with:
          project_type: miniProgram
          action_type: preview
          project_path: ./_example
          version: ${{ github.ref_name }}
          es6: true
          es7: true
          minify: true
        env: 
          MINI_APP_ID: ${{ secrets.APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: comment-with-qrcode
        uses: actions-cool/maintain-one-comment@v2.0.0
        with:
          token: ${{ secrets.PAT }}
          body: <img alt="qrcode" src="${{ steps.preview.outputs.preview-qrcode }}" />
