name: PREVIEW

on:
  issue_comment:
    types: [created]

jobs:
  request-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '预览'
    steps:
      - run: |
          timestamp=$(date +%s)
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT
        id: time
      - name: echo event
        run: |
          echo $headref
          echo $headsha
          echo $baseref
        env:
          headref: ${{github.event.pull_request.head_ref}}
          headsha: ${{github.event.pull_request.head.sha}}
          baseref: ${{github.event.pull_request.base_ref}}
      - name: Previous Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            正在构建预览的二维码，请稍等...
          comment_tag: ${{steps.time.outputs.timestamp}}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.6.0'
      - run: cd miniprogram && npm install
        shell: bash
      - name: get preview qrcode
        id: preview
        uses: LeeJim/setup-miniprogram@main
        with:
          project_type: miniProgram
          action_type: preview
          need-pack-npm: true
          project_path: ./miniprogram
          version: ${{ github.ref_name }}
          es6: true
          es7: true
          minify: true
        env: 
          MINI_APP_ID: ${{ secrets.APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Upload qrcode to Tencent COS
        uses: LeeJim/tencent-cos-action@main
        id: cos
        with:
          secretId: ${{ secrets.TENCENT_COS_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_COS_SECRET_KEY }}
          bucket: mp-qrcode-1255404841
          region: ap-guangzhou
          content: ${{ steps.preview.outputs.preview-qrcode }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <img alt="qrcode" src="${{ steps.cos.outputs.url }}" width="256" />
          comment_tag: ${{steps.time.outputs.timestamp}}
